### ISSUE TITLE
bug : 無法新增聯絡人

### ISSUE THREAD

**Issue by ChungChiuHung** [PIMIYA/Odoo_15#13]
當嘗試新增聯絡人時，會出現下列警示 : 
![image](https://user-images.githubusercontent.com/52248840/170906942-aa2f3ca8-cf00-4272-916d-df3791400932.png)

**Comment by HsienYu** [comment]
我沒有這個問題誒？

**Comment by ChungChiuHung** [comment]
蝦米 是因為我的browser 的關係ㄇ? 還是cloud server 的問題啊?

**Comment by ChungChiuHung** [comment]
我從新開啟無痕視窗登入後 就可以惹... 問題不詳

**Comment by ChungChiuHung** [comment]
問題來自於多公司，選擇MyCompany後 就不會產生此問題。
