### ISSUE TITLE
對帳單/收據 參考格式

### ISSUE THREAD

**Issue by ChungChiuHung** [PIMIYA/Odoo_15#16]
@seanmars 麻煩囉
### PDF Format
- [對帳單](https://docs.google.com/spreadsheets/d/1aDQt_NLV0tzMXGqssJmjMZrzQqeJW5XV9EiLmLTWDM4/edit#gid=0)
- [收據](https://docs.google.com/spreadsheets/d/1aDQt_NLV0tzMXGqssJmjMZrzQqeJW5XV9EiLmLTWDM4/edit#gid=1141569871)

**Comment by seanmars** [comment]
好，我試試，但不確定有沒有辦法 style 都一樣， layout 應該可以差不多
另外麻煩提供一下 logo 圖檔，謝謝

**Comment by ChungChiuHung** [comment]
Style不要求一樣
只要項目名稱正確，就可以了。
另外 小數點的部分 請參考連結 好了 圖片  我會先拿掉 ( 因為剛剛客戶又認真的看一次...所以又改了)

**Comment by ChungChiuHung** [comment]
@seanmars 
[Logo here](https://drive.google.com/drive/folders/15EDK00J_anIzTt5c9ynVb0AokLHIAL6U?usp=sharing)

**Comment by seanmars** [comment]
Settings -> Users & Companies -> Companies 
進入以上路徑設定 logo

**Comment by seanmars** [comment]
暫時還缺少 戶名、帳號、銀行 會計相關資料

**Comment by seanmars** [comment]
戶名、帳號、銀行 已增加
