### ISSUE TITLE
UI Layout

### ISSUE THREAD

**Issue by ChungChiuHung** [PIMIYA/Odoo_15#22]
- 磅單 (@HsienYu )
-  [x] 隱藏欄位: 收購價格(新台幣/百台斤)
-  [x] 顯示欄位: 稻穀總重(公斤) 
-  [x] #23

- 對帳單/收據/SellerName (@seanmars )
-  [x] 隱藏欄位: 磅單編號
-  [x] 隱藏欄位: 狀態
-  [x] 改變顯示方式: 磅單成立日期顯示格式 => 2022/06/01
-  [x] 顯示欄位: 乾穀總重
-  [x] 單價 : 元/公斤
-  [x] 顯示欄位: 戶名
-  [x] 顯示欄位: 帳號
-  [x] 顯示欄位: 銀行

**Comment by HsienYu** [comment]
ok

**Comment by HsienYu** [comment]
顯示欄位: 戶名
顯示欄位: 帳號
顯示欄位: 銀行

這個是也要顯示在archived的form view 中嗎？

**Comment by ChungChiuHung** [comment]
是啊 這三個項目也需要放在
Archived view 
在麻煩了，感謝

**Comment by seanmars** [comment]
已修正
