### ISSUE TITLE
PDF Layout :秤量傳票（濕穀）

### ISSUE THREAD

**Issue by ChungChiuHung** [PIMIYA/Odoo_15#26]
- 列印範圍超出頁面
- ![image](https://user-images.githubusercontent.com/52248840/171572979-77d0d34e-b7bf-45e6-9410-1a1a09acfb54.png)

- 傳票內容 : 缺少部分數據
   - [x] 乾濕穀轉換率(%) : WetToDryRatio
   - [x] 乾穀總重 : CropWeight_by_ratio
-  ![image](https://user-images.githubusercontent.com/52248840/171574895-400fb74d-7759-4ac9-814a-a87a1e43ee87.png)

**Comment by seanmars** [comment]
已修正
