### ISSUE TITLE
PDF Layout : 字體放大

### ISSUE THREAD

**Issue by ChungChiuHung** [PIMIYA/Odoo_15#27]
磅單
對帳單/收據

**Comment by ChungChiuHung** [comment]
農民大多數以上年紀，請協助使用較大的字體顯示喔 感謝

**Comment by seanmars** [comment]
我會盡量調整，但能放大限度有限，因為太大就會超出一頁

**Comment by seanmars** [comment]
調整了一版 2eac8bd63d7c2538627bf7063d6428bb9adac1a5 到時候測試看看，我盡量拉大+測試了一下，有可能還會有跑版情況，再回報給我
