### ISSUE TITLE
修改自帶的模組欄位能提供更改的addon名稱嗎?

### ISSUE THREAD

**Issue by YLiu4129** [PIMIYA/Odoo_15#30]
修改自帶的模組欄位能提供更改的addon名稱嗎? 或者是否有辦法查詢該欄位的addon出處? 我好像只能在__manifest__.py depends看到依賴的addon

![image](https://user-images.githubusercontent.com/51956278/172525625-af683342-32d1-4892-a779-031a29103244.png)
![image](https://user-images.githubusercontent.com/51956278/172525749-d4cafc61-ce63-436a-a01c-5904a3cf70e8.png)

Contacts addon不存在 is an agriculture member欄位的翻譯

**Comment by seanmars** [comment]
請開啟 odoo debug mode 即可在網頁上觀看相關資訊
相關連結 > [Debug Mode](https://www.odoo.com/documentation/15.0/applications/general/developer_mode.html)

**Comment by YLiu4129** [comment]
OK，找到了! 是在inherit_res_partner.py
