### ISSUE TITLE
烘乾費用未帶入/顯示 => 稻穀收購管理/對帳單/收據

### ISSUE THREAD

**Issue by ChungChiuHung** [PIMIYA/Odoo_15#37]
![image](https://github.com/PIMIYA/Odoo_15/assets/52248840/e4c6b5a7-29f6-4615-975b-8db4b8d72ced)

將烘乾費用 顯示至 應收/應付款項

一個農民會有多筆磅單
因此也會有多筆 烘乾費用。

**Comment by HsienYu** [comment]
已更新自動新增烘乾費至應收款項
