### ISSUE TITLE
換算乾穀/新增欄位

### ISSUE THREAD

**Issue by ChungChiuHung** [PIMIYA/Odoo_15#5]
- [x] 新增欄位
- Cell 1: 乾穀折換率(WetToDryRatio)

- [x] 新增邏輯判斷&計算式
- `If CropStatus == 乾穀:  WetToDryRatio = 100`
- `If CropStatus == 濕穀:  WetToDryRatio = 100 - RawHumidity + 8`
- `CropWeight = CropWeight * WetToDryRatio`

**Comment by HsienYu** [comment]
CropWeight = CropWeight * WetToDryRatio ？？？
WetToDryRatio 是不是要除以100再相乘？

**Comment by ChungChiuHung** [comment]
Yes 我錯了 是百分比 才對
